numero = int(input("Qual número você quer ver a tabuada de multiplicação: "))
print('{:*^20}'.format(' Taboada de '+str(numero)+' '))
print('{} x {} = {:2}'.format(numero, 0, numero * 0))
print('{} x {} = {:2}'.format(numero, 1, numero * 1))
print('{} x {} = {:2}'.format(numero, 2, numero * 2))
print('{} x {} = {:2}'.format(numero, 3, numero * 3))
print('{} x {} = {:2}'.format(numero, 4, numero * 4))
print('{} x {} = {:2}'.format(numero, 5, numero * 5))
print('{} x {} = {:2}'.format(numero, 6, numero * 6))
print('{} x {} = {:2}'.format(numero, 7, numero * 7))
print('{} x {} = {:2}'.format(numero, 8, numero * 8))
print('{} x {} = {:2}'.format(numero, 9, numero * 9))
print('*' * 20)

"""numero = int(input('Qual número você quer ver a taboada de multiplicação?: '))
print('{:_^20}'.format('Taboada de '+str(numero)))
print(numero, 'x 0 =', (numero * 0))
print(numero, 'x 1 =', (numero * 1))
print(numero, 'x 2 =', (numero * 2))
print(numero, 'x 3 =', (numero * 3))
print(numero, 'x 4 =', (numero * 4))
print(numero, 'x 5 =', (numero * 5))
print(numero, 'x 6 =', (numero * 6))
print(numero, 'x 7 =', (numero * 7))
print(numero, 'x 8 =', (numero * 8))
print(numero, 'x 9 =', (numero * 9))
print(numero, 'x 10 =', (numero * 10))
print('_' * 20)"""